Repository ESC-CoM/esc-client, pull requests merged in 2022-06, with the labels that each got.

#75 [feat] 회원가입 항목 별 페이지 분리 & 상태관리 zustand 적용
  package.json
  src/App.tsx
  src/app/hooks.ts
  src/app/store.ts
  src/components/Join/BasicInfo/EmailInput/index.tsx
  src/components/Join/BasicInfo/EmailInput/style.module.scss
  src/components/Join/BasicInfo/PasswordInput/index.tsx
  src/components/Join/BasicInfo/PasswordInput/style.module.scss
  src/components/Join/BasicInfo/PhoneAuth/authTimer.tsx
  src/components/Join/BasicInfo/PhoneAuth/index.tsx
  src/components/Join/BasicInfo/PhoneAuth/style.module.scss
  src/components/Join/BasicInfo/index.tsx
  src/components/Join/BasicInfo/style.module.scss
  src/components/Join/BasicInfo/yup.tsx
  src/components/Join/MoreInfo/BirthInput/index.tsx
  src/components/Join/MoreInfo/BirthInput/style.module.scss
  src/components/Join/MoreInfo/Drink/drink.tsx
  src/components/Join/MoreInfo/Drink/index.tsx
  src/components/Join/MoreInfo/Drink/style.module.scss
  src/components/Join/MoreInfo/GenderInput/index.tsx
  src/components/Join/MoreInfo/GenderInput/style.module.scss
  src/components/Join/MoreInfo/HeightInput/index.tsx
  src/components/Join/MoreInfo/HeightInput/style.module.scss
  src/components/Join/MoreInfo/MbtiInput/index.tsx
  src/components/Join/MoreInfo/MbtiInput/style.module.scss
  src/components/Join/MoreInfo/WeightInput/index.tsx
  src/components/Join/MoreInfo/WeightInput/style.module.scss
  src/components/Join/MoreInfo/index.tsx
  src/components/Join/MoreInfo/style.module.scss
  src/components/Join/MoreInfo/yup.tsx
  src/components/Join/NextButton/index.tsx
  src/components/Join/NextButton/style.module.scss
  src/components/Join/Term/index.tsx
  src/components/Join/Term/style.module.scss
  src/components/Join/index.ts
  src/features/counter/counterSlice.ts
  src/pages/Join/basic.tsx
  src/pages/Join/emailPasswordInputPage.tsx
  src/pages/Join/index.ts
  src/pages/Join/moreInfoPage1.tsx
  src/pages/Join/moreInfoPage2.tsx
  src/pages/Join/phoneAuthPage.tsx
  src/pages/Join/style.module.scss
  src/routes/JoinRoute.tsx
  src/store/useStore.tsx
  src/styles/_mixin.scss
  src/types/join.ts
  src/utils/adjustDrink.ts
  src/utils/index.ts
  src/utils/insertAutoHyphen.ts
  yarn.lock
Labels: 💻 Feature, ♻︎ Refactor, 💇🏼‍♂️ UI/UX

#88 [Bug] 필요없는 파일 삭제
  src/pages/Join/more.tsx
  src/pages/MyMeeting/MyMeetingPage.tsx
  src/pages/MyMeeting/RegisterMeetingDetailPage.tsx
  src/pages/MyMeeting/index.ts
Labels: 🐞 Bug, 🙌 self-approve

#81 [feat] 내 과팅 이미지 lazy loading & infinite scroll
  src/__mocks__/myMeeting.ts
  src/components/MyMeeting/RegisterMeeting/RegisterDetail/index.tsx
  src/components/MyMeeting/RegisterMeeting/RequestedList/index.tsx
  src/components/MyMeeting/RegisterMeeting/RequestedList/style.module.scss
  src/components/MyMeeting/RegisterMeeting/index.tsx
  src/components/MyMeeting/RegisterMeeting/style.module.scss
  src/components/MyMeeting/RequestMeeting/index.tsx
  src/components/MyMeeting/RequestMeeting/style.module.scss
  src/components/MyMeeting/index.ts
  src/pages/MyMeetingPages/RegisterDetailPage.tsx
  src/pages/MyMeetingPages/RegisterPage.tsx
  src/pages/MyMeetingPages/RequestPage.tsx
  src/pages/MyMeetingPages/index.tsx
  src/pages/MyMeetingPages/style.module.scss
  src/styles/_mixin.scss
  src/types/myMeeting.ts
Labels: 💻 Feature, ♻︎ Refactor

#71 [feat] 내 정보 페이지 마크업
  .gitignore
  src/App.tsx
  src/components/MyPage/CardBox/index.tsx
  src/components/MyPage/CardBox/style.module.scss
  src/components/MyPage/EditButton/index.tsx
  src/components/MyPage/EditButton/style.module.scss
  src/components/MyPage/MyInfomationCard/index.tsx
  src/components/MyPage/MyInfomationCard/style.module.scss
  src/components/MyPage/PrivateInformationCard/index.tsx
  src/components/MyPage/PrivateInformationCard/style.module.scss
  src/components/MyPage/index.ts
  src/pages/MyPage/index.tsx
  src/styles/_color.scss
  src/styles/_mixin.scss
Labels: 💻 Feature, 💇🏼‍♂️ UI/UX

#84 [feat] 설정 페이지 마크업
  src/App.tsx
  src/components/Setting/Container/index.tsx
  src/components/Setting/Container/style.module.scss
  src/components/Setting/LinkBar/index.tsx
  src/components/Setting/LinkBar/style.module.scss
  src/components/Setting/SettingBox/index.tsx
  src/components/Setting/SettingBox/style.module.scss
  src/components/Setting/ToggleBar/index.tsx
  src/components/Setting/ToggleBar/style.module.scss
  src/constants/headerMenus.tsx
  src/pages/Setting/Basic.tsx
  src/pages/Setting/Detail.tsx
  src/pages/Setting/index.ts
  src/routes/SettingRouter.tsx
  src/types/setting.ts
  src/utils/getBarClassName.ts
Labels: 💻 Feature, 💇🏼‍♂️ UI/UX
