Repository ESC-CoM/esc-client, pull requests merged in 2022-03, with the labels that each got.

#14 [feat] 개인 정보 동의 페이지
  src/components/Join/ToS/index.tsx
  src/components/Join/ToS/style.module.scss
  src/components/Join/ToS/yup.tsx
  src/components/Join/index.ts
Labels: 💻 Feature, 🙌 self-approve, 💇🏼‍♂️ UI/UX

#13 [feat] 시작 페이지 마크업
  src/components/Start/index.tsx
  src/components/Start/style.module.scss
Labels: 💻 Feature, 📱 Mobile, 💇🏼‍♂️ UI/UX

#15 [feat] 회원가입(join) 기능 페이지
  .eslintrc
  package.json
  src/components/Join/BasicJoin/index.tsx
  src/components/Join/BasicJoin/style.module.scss
  src/components/Join/BasicJoin/yup.tsx
  src/components/Join/Personality/index.tsx
  src/components/Join/Terms/index.tsx
  src/components/Join/Terms/style.module.scss
  src/components/Join/Terms/yup.tsx
  src/components/Join/index.ts
  src/components/Layout/Footer/style.module.scss
  src/styles/_color.scss
  src/styles/_mixin.scss
  src/styles/reset.scss
  yarn.lock
Labels: 💻 Feature, 💇🏼‍♂️ UI/UX
