Repository ESC-CoM/esc-client, pull requests merged in 2023-04, with the labels that each got.

#260 [Feat] CI 스크립트 작성 및 의존성 캐싱
  .github/actions/yarn-install/action.yml
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/lighthouse.yml
  .lighthouserc.js
  package.json
  src/pages/MyMeetingPages/RegisterPage.tsx
Labels: 💻 Feature, ⚙️ Setting

#262 [Feat] CD 스크립트 작성
  .github/workflows/continuous-deployment.yml
Labels: 🌐 Deploy, 💻 Feature

#257 [Refactor] 내가 등록한 과팅 API 연결 리팩토링, API타입 리팩토링, useCoreInfiniteQuery 기능 추상화
  src/api/board/index.ts
  src/components/MyMeeting/RegisterMeeting/RequestedItem/index.tsx
  src/components/MyMeeting/RequestMeeting/index.tsx
  src/hooks/api/board/index.ts
  src/hooks/api/borad/index.ts
  src/hooks/api/core/index.ts
  src/hooks/api/home/index.ts
  src/hooks/useDetectScroll.ts
  src/mocks/data/myMeeting.ts
  src/mocks/data/pagination.ts
  src/mocks/handlers/myMeetingHandlers.ts
  src/pages/Meeting/MeetingHome/index.tsx
  src/pages/MyMeetingPages/RegisterDetailPage.tsx
  src/pages/MyMeetingPages/RegisterPage.tsx
  src/pages/MyMeetingPages/RequestPage.tsx
  src/types/apiTypes/auth.d.ts
  src/types/apiTypes/board.d.ts
  src/types/apiTypes/friend.d.ts
  src/types/apiTypes/home.d.ts
  src/types/apiTypes/join.d.ts
  src/types/apiTypes/state.d.ts
  src/types/apiTypes/user.d.ts
Labels: 📡 API, 💻 Feature, ♻︎ Refactor

#267 [Feat] CD 워크플로우 트리거를 CI로 설정하기
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: 🌐 Deploy, 💻 Feature

#268 [Feat] husky 적용
  .husky/pre-commit
  package.json
  yarn.lock
Labels: 💻 Feature, ⚙️ Setting
